# Generated by Django 6.0.4 on 2026-05-05 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('text', models.TextField()),
                ('author_id', models.CharField(blank=True, max_length=32)),
                ('author_username', models.CharField(blank=True, max_length=255)),
                ('lang', models.CharField(blank=True, max_length=16)),
                ('post_created_at', models.DateTimeField(help_text='Created time from X (UTC stored with timezone).')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'X post',
                'verbose_name_plural': 'X posts',
                'ordering': ['-post_created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='0 = very unhappy … 4 = neutral … 9 = extremely happy (weather-related).')),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=64)),
                ('rationale', models.TextField(blank=True)),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='tracker.xpost')),
            ],
            options={
                'verbose_name': 'sentiment analysis',
                'verbose_name_plural': 'sentiment analyses',
                'ordering': ['-classified_at'],
            },
        ),
    ]
